// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {discovery} from '../models';

export function AddFolder(arg1:string,arg2:string):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetFolders():Promise<Array<config.Folder>>;

export function GetPeers():Promise<Array<discovery.Peer>>;

export function GetSubscriptions():Promise<Array<config.Subscription>>;

export function OpenFolderDialog():Promise<string>;

export function RemoveFolder(arg1:string):Promise<void>;

export function SetFolderMode(arg1:string,arg2:string):Promise<void>;

export function Subscribe(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Unsubscribe(arg1:string,arg2:string):Promise<void>;

export function UpdateBaseStorage(arg1:string):Promise<void>;

export function UpdateDisplayName(arg1:string):Promise<void>;

export function UpdatePort(arg1:number):Promise<void>;
