// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolder(arg1) {
  return window['go']['main']['App']['AddFolder'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFolders() {
  return window['go']['main']['App']['GetFolders']();
}

export function GetPeerFolders(arg1) {
  return window['go']['main']['App']['GetPeerFolders'](arg1);
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function GetSubscriptions() {
  return window['go']['main']['App']['GetSubscriptions']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function RemoveFolder(arg1) {
  return window['go']['main']['App']['RemoveFolder'](arg1);
}

export function SetFolderSharing(arg1, arg2) {
  return window['go']['main']['App']['SetFolderSharing'](arg1, arg2);
}

export function Subscribe(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Subscribe'](arg1, arg2, arg3, arg4);
}

export function Unsubscribe(arg1, arg2) {
  return window['go']['main']['App']['Unsubscribe'](arg1, arg2);
}

export function UpdateBaseStorage(arg1) {
  return window['go']['main']['App']['UpdateBaseStorage'](arg1);
}

export function UpdateDisplayName(arg1) {
  return window['go']['main']['App']['UpdateDisplayName'](arg1);
}

export function UpdatePort(arg1) {
  return window['go']['main']['App']['UpdatePort'](arg1);
}
